export default {
  login: "mohandeoche",
  id: 69669180,
  node_id: "MDQ6VXNlcjY5NjY5MTgw",
  avatar_url: "https://avatars.githubusercontent.com/u/69669180?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/mohandeoche",
  html_url: "https://github.com/mohandeoche",
  followers_url: "https://api.github.com/users/mohandeoche/followers",
  following_url:
    "https://api.github.com/users/mohandeoche/following{/other_user}",
  gists_url: "https://api.github.com/users/mohandeoche/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/mohandeoche/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/mohandeoche/subscriptions",
  organizations_url: "https://api.github.com/users/mohandeoche/orgs",
  repos_url: "https://api.github.com/users/mohandeoche/repos",
  events_url: "https://api.github.com/users/mohandeoche/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/mohandeoche/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: "Pune",
  email: null,
  hireable: null,
  bio: "Front end Developer | React | Python | HTML | CSS | DevOps | DataAnalyst",
  twitter_username: null,
  public_repos: 1,
  public_gists: 0,
  followers: 3,
  following: 0,
  created_at: "2020-08-14T07:27:52Z",
  updated_at: "2021-05-16T05:06:03Z",
};
